version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile.backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - code-executor

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
    depends_on:
      - backend

  # Code execution service (used by backend)
  code-executor:
    image: shodh/code-executor
    build:
      context: ./backend
      dockerfile: src/main/docker/Dockerfile
    volumes:
      - code-execution-volume:/workspace

volumes:
  code-execution-volume: